stages:
  data_ingestion:
    cmd: python src/cloner/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cloner/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/LJSpeech-1.1

  data_preprocessing:
    cmd: python src/cloner/pipeline/stage_02_data_preprocessing.py
    deps:
      - src/cloner/pipeline/stage_02_data_preprocessing.py
      - config/config.yaml
      - params.yaml
    outs:
      - artifacts/data_preprocessing/processed_audio

  model_training:
    cmd: python src/cloner/pipeline/stage_03_model_training.py
    always_changed: false
    deps:
      - src/cloner/pipeline/stage_03_model_training.py
      - config/config.yaml
      - params.yaml
    outs:
      - artifacts/model_training/output