tune_params:
  sample_rate: 22050
  num_mels: 80
  fft_size: 2400
  frame_length_ms: 50
  frame_shift_ms: 12.5
  hop_length: null
  win_length: 1024
  preemphasis: 0.98
  min_level_db: -100
  ref_level_db: 0
  power: 1.5
  griffin_lim_iters: 60
  mel_fmin: 0.0
  mel_fmax: 8000.0
  do_trim_silence: true

reset:
  signal_norm: True  
  stats_path: null
  symmetric_norm: False
  max_norm: 1
  clip_norm: True

audio_config:
  sample_rate: 22050
  win_length: 1024
  hop_length: 256
  fft_size: 1024
  num_mels: 80
  mel_fmin: 0
  mel_fmax: null
  power: 1.5
  preemphasis: 0.98
  ref_level_db: 0

model_config:
  audio: audio_config
  run_name: vits_ljspeech
  batch_size: 8
  eval_batch_size: 3
  batch_group_size: 2
  num_loader_workers: 4
  num_eval_loader_workers: 4
  run_eval: True
  test_delay_epochs: -1
  epochs: 1
  text_cleaner: english_cleaners
  use_phonemes: True
  phoneme_language: en-us
  phoneme_cache_path: os.path.join(output_path, "phoneme_cache")
  compute_input_seq_cache: True
  print_step: 25
  print_eval: True
  mixed_precision: True 
  output_path: artifacts/model_training/output
  datasets: [dataset_config]
  cudnn_benchmark: False
